server:
  port: 1400
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: userServer
          uri: http://127.0.0.1:1010
          predicates:
            - Path=/UserController/**
        -
          id: deliveryAddressServer
          uri: http://127.0.0.1:1050
          predicates:
            - Path=/DeliveryAddressController/**

        - id: cartServer
          uri: http://127.0.0.1:1040
          predicates:
            - Path=/CartController/**

        - id: businessServer
          uri: http://127.0.0.1:1030
          predicates:
            - Path=/BusinessController/**

        - id: foodServer
          uri: http://127.0.0.1:1020
          predicates:
            - Path=/FoodController/**

        - id: orderServer
          uri: http://127.0.0.1:1060
          predicates:
            - Path=/OrderController/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            # 允许跨域的源(网站域名/ip)，设置*为全部
#            allowedOrigins: "*"
#            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
#            allowedMethods: "*"
#            # 允许跨域请求里的head字段，设置*为全部
#            allowedHeaders: "*"

#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#          '[/**]':
#            allowed-origins: "*"
#            allowed-headers: "*"
#            allowed-methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE